<?php

use App\Models\Notification;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use Livewire\Volt\Volt;

Route::get('/', [App\Http\Controllers\WelcomeController::class, 'index']);


Route::view('dashboard', 'dashboard')
    ->middleware(['auth', 'verified'])
    ->name('dashboard');

Route::view('profile', 'profile')
    ->middleware(['auth'])
    ->name('profile');

Volt::route('flights', 'flights')
    ->middleware(['auth'])
    ->name('flights');

Volt::route('my-bookings', 'my-bookings')
    ->middleware(['auth'])
    ->name('my-bookings');

Volt::route('file-pirep', 'file-pirep')
    ->middleware(['auth'])
    ->name('file-pirep');

Volt::route('my-pireps', 'my-pireps')
    ->middleware(['auth'])
    ->name('my-pireps');

Volt::route('simbrief', 'simbrief')
    ->middleware(['auth'])
    ->name('simbrief');

Volt::route('live-map', 'live-map')->name('live-map');

Volt::route('pilot-profile/{pilotId}', 'pilot-profile')->name('pilot-profile');

Volt::route('pilot-roster', 'pilot-roster')->name('pilot-roster');

Volt::route('pilot-stats', 'pilot-stats')
    ->middleware(['auth'])
    ->name('pilot-stats');

Volt::route('leaderboard', 'leaderboard')->name('leaderboard');

Volt::route('handbook', 'handbook')->name('handbook');

Volt::route('/page/{slug}', 'custom-page')->name('custom-page');

Volt::route('acars', 'acars')
    ->middleware(['auth'])
    ->name('acars');

Volt::route('flight-history', 'flight-history')
    ->middleware(['auth'])
    ->name('flight-history');

Volt::route('achievements', 'achievements')
    ->middleware(['auth'])
    ->name('achievements');

Volt::route('tours', 'tours')
    ->middleware(['auth'])
    ->name('tours');

Volt::route('airports', 'airports')
    ->name('airports');


Route::get('/page/{slug}', function ($slug) {
    $page = App\Models\CustomPage::published()->where('slug', $slug)->firstOrFail();
    return view('page', compact('page'));
})->name('page');


Route::middleware('auth')->group(function () {
    Route::get('/notifications/unread', function (Request $request) {
        $notifications = $request->user()->notifications()->take(20)->get();
        return response()->json([
            'unread' => $request->user()->unreadNotifications()->count(),
            'notifications' => $notifications,
        ]);
    });

    Route::get('/pireps/{pirep}/export', function (Request $request, \App\Models\Pirep $pirep) {
        if ($pirep->user_id !== $request->user()->id && !$request->user()->isStaff()) {
            abort(403);
        }

        $content = "Atlantic Star Airways - PIREP Export\n";
        $content .= str_repeat('=', 50) . "\n\n";
        $content .= "Flight:    {$pirep->flight_number}\n";
        $content .= "Route:     {$pirep->departure} → {$pirep->arrival}\n";
        $content .= "Aircraft:  {$pirep->aircraft_registration} ({$pirep->aircraft_icao})\n";
        $content .= "Time:      {$pirep->flight_time}h\n";
        $content .= "Landing:   {$pirep->landing_rate} fpm\n";
        $content .= "Score:     {$pirep->score}\n";
        $content .= "Status:    {$pirep->status}\n";
        $content .= "Submitted: {$pirep->submitted_at?->format('d M Y H:i')}\n\n";
        if ($pirep->route) {
            $content .= "Route String:\n{$pirep->route}\n\n";
        }
        if ($pirep->log) {
            $content .= "Flight Log:\n{$pirep->log}\n\n";
        }
        $content .= str_repeat('-', 50) . "\n";
        $content .= "Generated by Atlantic Star Airways CMS\n";

        return response($content, 200, [
            'Content-Type' => 'text/plain',
            'Content-Disposition' => 'attachment; filename="PIREP_' . $pirep->flight_number . '_' . $pirep->departure . '-' . $pirep->arrival . '.txt"',
        ]);
    })->name('pireps.export');

    // SimBrief OFP PDF proxy – streams the PDF so it can be embedded in an iframe
    Route::get('/simbrief/ofp-pdf', function (Request $request) {
        $url = $request->query('url', '');

        // Security: only allow simbrief.com URLs
        $parsed = parse_url($url);
        $host = strtolower($parsed['host'] ?? '');
        if (!$url || !str_ends_with($host, 'simbrief.com')) {
            abort(403, 'Invalid PDF URL.');
        }

        try {
            $response = \Illuminate\Support\Facades\Http::timeout(30)->get($url);
            if (!$response->successful()) abort(404);

            return response($response->body(), 200, [
                'Content-Type'        => 'application/pdf',
                'Content-Disposition' => 'inline; filename="OFP.pdf"',
                'X-Frame-Options'     => 'SAMEORIGIN',
            ]);
        } catch (\Exception $e) {
            abort(500, 'Could not fetch PDF.');
        }
    })->name('simbrief.ofp-pdf');

    Route::post('/notifications/read-all', function (Request $request) {
        $request->user()->unreadNotifications->markAsRead();
        return response()->json(['success' => true]);
    });
});

Route::post('/logout', function () {
    auth()->logout();
    request()->session()->invalidate();
    request()->session()->regenerateToken();
    return redirect('/');
})->middleware('auth')->name('logout');

Route::middleware(['auth', 'verified', 'admin'])->prefix('admin')->name('admin.')->group(function () {
    Volt::route('/', 'admin.dashboard')->name('dashboard');
    Volt::route('/fleet', 'admin.fleet')->name('fleet');
    Volt::route('/schedules', 'admin.schedules')->name('schedules');
    Volt::route('/pilots', 'admin.pilots')->name('pilots');
    Volt::route('/news', 'admin.news')->name('news');
    Volt::route('/settings', 'admin.settings')->name('settings');
    Volt::route('/pages', 'admin.custom-pages')->name('pages');

    Route::get('/export/pilots/csv', [App\Http\Controllers\Admin\ExportController::class, 'pilotsCsv'])->name('export.pilots.csv');
    Route::get('/export/pilots/print', [App\Http\Controllers\Admin\ExportController::class, 'pilotsPrint'])->name('export.pilots.print');
    Route::get('/export/pireps/csv', [App\Http\Controllers\Admin\ExportController::class, 'pirepsCsv'])->name('export.pireps.csv');

    Volt::route('/activity-log', 'admin.activity-log')->name('activity-log');
});

Route::middleware(['auth', 'verified', 'staff'])->prefix('staff')->name('staff.')->group(function () {
    Volt::route('/', 'admin.staff.index')->name('dashboard');
    Volt::route('/roles', 'admin.staff.roles')->name('roles');
});

require __DIR__.'/auth.php';
